services:
  brouter:
    restart: unless-stopped
    image: jimoshea89/brouter:amd64
    volumes:
      - ./segments4:/segments4
  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - brouter
